spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dingdong_party?useUnicode=true&characterEncoding=utf-8
    username: dingdongParty
    password: achobeta

  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 1800000
    password: achobeta

server:
  port: 18801