spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxxx:3306/dingdong_party?useUnicode=true&characterEncoding=utf-8
    username: xxxx
    password: xxxx

  redis:
    host: xxxx
    port: 6379
    database: 0
    timeout: 1800000
    password: xxxx


# redis 不用密码（测试环境）
management:
  health:
    redis:
      enabled: false

server:
  port: 8003
  servlet:
    session:
      timeout: 1200