spring:
  profiles:
    active: pro

  application:
    name: service-admin
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:18001/eureka,http://localhost:18002/eureka
  instance:
    instance-id: service-admin

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mybatis/mapper/*.xml

wx:
  open:
    # 微信开放平台 appid
    app_id: xxxx
    # 微信开放平台 appsecret
    app_secret: xxxx
    # 公众号 openid
    open_id: xxxx

application:
  login-url: /login
  image-code-url: /image-code
  logout-url: /logout
